/* Generated By:CSharpCC: Do not edit this line. MiniCSharpParserConstants.cs */
namespace ModernCompilerImplementation.Chapter2.CSharpCC.Lib{

/// <summary>
/// Token literal values and constants.
/// <summary>
public class MiniCSharpParserConstants {

  /// <summary> End of File</summary>
  public const int EOF = 0;
  /// <summary>RegularExpression Id.</summary>
  public const int IF = 1;
  /// <summary>RegularExpression Id.</summary>
  public const int DIGIT = 2;
  /// <summary>RegularExpression Id.</summary>
  public const int ID = 3;
  /// <summary>RegularExpression Id.</summary>
  public const int NUM = 4;
  /// <summary>RegularExpression Id.</summary>
  public const int REAL = 5;

  /// <summary>Lexical state.</summary>
  public const int DEFAULT = 0;

  /// <summary>Literal token values.</summary>
  public static readonly string[] TokenImage = {
    "<EOF>",
    "\"if\"",
    "<DIGIT>",
    "<ID>",
    "<NUM>",
    "<REAL>",
    "<token of kind 6>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
}
